### ISSUE TITLE
Small bug in accuracy computation

### ISSUE THREAD

**Issue by tscohen** [mitmul/chainer-cifar10#1]
In both train() and validate(), the loss and accuracy on a minibatch are multiplied by args.batchsize instead of the true size of the minibatch. When the batchsize does not evenly divide the size of the dataset, the last batch is smaller than batchsize. To fix this, replace the "\* args.batchsize" by "*y_batch.size".

**Comment by mitmul** [comment]
Thank you for your feedback. I fixed that in https://github.com/mitmul/chainer-cifar10/commit/ae7d7038ff57b9124037b256993c7a87398d1d1b.
