### ISSUE TITLE
A minor typo in `dataset.py`

### ISSUE THREAD

**Issue by kaniblu** [mitmul/chainer-cifar10#3]
There is a typo in line 83 where the label array is cast into `int32` type then stored in `training_labell`. Fortunately, the typo doesn't affect the outcome of the script though.

Another thing: I suggest using `numpy.ndarray.astype` method for casting types instead of redefining the array, as the former is a little more optimized than the latter.

**Comment by mitmul** [comment]
Thank you for letting me know that typo. I fixed that with [this commit](https://github.com/mitmul/chainer-cifar10/commit/7eda1c99c2f56101eca812340c2a5a79e232a596#diff-b24696c07a0a52292a89d29937161fcfR83).
